### PR TITLE
Add support for multiselect folder browser

### PR DESCRIPTION
**Pull request by lozo2010**

### CODE REVIEW

**Comment by augustoproiete** [comment]
Thanks @lozo2010 looks promising. Do you mind writing a comment on https://github.com/ookii-dialogs/ookii-dialogs-wpf/issues/29 (can be anything) just so that GitHub can allow me to assign the issue to you?

**Comment by lozo2010** [comment]
> Thanks @lozo2010 looks promising. Do you mind writing a comment on #29 (can be anything) just so that GitHub can allow me to assign the issue to you?

Yes!

**Review by augustoproiete — APPROVED** [review]
LGTM!

**Comment by augustoproiete** [comment]
@lozo2010 your changes have been merged, thanks for your contribution :+1:

**Pull request merged**
