### PR TITLE
Use Microsoft.Windows.CsWin32 to generate P/Invoke methods

### PR DESCRIPTION
**Pull request by virzak**

### CODE REVIEW

**Comment by augustoproiete** [comment]
Thanks for the PR @virzak ! 👍🏻

Could you create an issue in this repo with the elevator pitch for moving to CsWin32 on this library? I'm definitely not against it, but I'd like to understand the value we get given all the P/Invoke definitions have already been written and have been battle tested for many years.

Also, if we were to go this route, would we be able to use a stable version of the `Microsoft.Windows.CsWin32` package directly from the nuget.org feed?

**Comment by virzak** [comment]
Logged #85.

Yes, the nuget.org version works as well. Something wasn't working during development and I just tried the latest build of the library. Turned out it wasn't at fault. If you'd like I can revert.

**Comment by virzak** [comment]
Now using the latest version from nuget instead of a private feed.

**Comment by virzak** [comment]
@augustoproiete, any chance of merging this soon? I'd like to submit another PR which conflicts with this, so if you have a chance to look at this soon, it would avoid future conflict.

**Comment by augustoproiete** [comment]
@virzak Merged. Sorry for the long delay

**Pull request merged**
